{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.pachd.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1656"
    prometheus.io/scrape: "true"
    {{- if .Values.pachd.service.annotations }}
    {{- toYaml .Values.pachd.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: pachd
    suite: pachyderm
    {{- if .Values.pachd.service.labels }}
    {{- toYaml .Values.pachd.service.labels | nindent 4 }}
    {{- end }}
  name: pachd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: api-grpc-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: {{ .Values.pachd.service.port }}
    {{- end }}
    port: {{ .Values.pachd.service.port }}
    protocol: TCP
    targetPort: api-grpc-port
  - name: oidc-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: {{ add .Values.pachd.service.port 7 }}
    {{- end }}
    port: {{ add .Values.pachd.service.port 7 }}
    targetPort: oidc-port
  - name: identity-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: {{ add .Values.pachd.service.port 8 }}
    {{- end }}
    port: {{ add .Values.pachd.service.port 8 }}
    targetPort: identity-port
  - name: s3gateway-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: {{ sub .Values.pachd.service.port 50 }}
    {{- end }}
    port: {{ sub .Values.pachd.service.port 50 }}  
    targetPort: s3gateway-port
  - name: prom-metrics
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: {{ add .Values.pachd.service.port 6 }}
    {{- end }}
    port: {{ add .Values.pachd.service.port 6 }}
    protocol: TCP
    targetPort: prom-metrics
  selector:
    app: pachd
  type: {{ .Values.pachd.service.type }}
{{- end }}
